### ISSUE TITLE
Design options: consider an S3? 

### ISSUE THREAD

**Issue by robertlipe** [ale1800/USB-C-PD-Led-Controller#1]
This is awesome! 

I'm on mobile, so reading the .Sch is hard, but I think i see esp32-wroom-32d which is the legacy module. 

If you would change to ESP32-S3 (exp. With more PSRAM) you'd have a more capable board. You could also eliminate serial bridge and get jtag with no extra pads or buffers. The USB could be used as any USB type (like a disk) or as a host (attach a keyboard). You might be able to get the 8MB PSRAM/16 MB Flash modules for not a lot more than the bom cost of the serial/USB bridge and needed additional transistors to make reset work on trailing edge of dtr and pulse EN. The CPU is also more efficient per clock and has more powerful instructions handy in this world doe FFT, like doing beat detection, as well as offering better memory model with less goofy fragmentation and fewer restrictions on where you can DMA to and from.

Element

Atomic14 has a YouTube video showing a super minimal S3 build it was a USB socket, lvdo, maybe one cap for the ENable signal on power up and ... not much more. (Edit: https://youtu.be/tQ0dL_9M1wI?si=FmXgR3vD-N_fcYg2 - and I'll admit that for a production board, I probably wouldn't chip quite so deeply. Decouplers actually DO have a purpose, but his underlying point that you can make a S3 with USB from almost nothing is legit.)

As disclosure, you could go S2 and get most of those benefits, but only on a single core. C3 is dirt cheap, but only single core and has a completely different arch, being 160Mhz RISC-V instead of 240Mhz XTENSA. While that may sound slower, they're more of a draw but some projects may not support single cores.

As a stuffing option, allow the external WiFi version and, for crazy talk, some screw terminals and a few diodes to stop people from using both, allow external DC from a random DC source that's bucked to power the esp32 and passed through to the rails of the strip. Same board, populated different ways, no real cost unless it results in fewer boards per panel.

If your chosen buck/boost could get to 24V (or your PD was so equipped, which seems likely in laptops and less so in a phone charger) you'd have an advantage of being able to run longer power runs without needing injection. Budget a GPIO, resistor, led to help figure out if their random USB-C source actually has PD and at the requested wattage combination. The industry has done a terrible job of teaching consumers what voltage any given USB source will actually source.

Without seeing the schematic,. I'll say that this is pretty close to a board I've considered building. Usb-c is just the way to go. I'm glad to see you tackling this! (So I don't have to. 😉)

This isn't meant to be terrifying feedback and when I'm near a computer again,. I can perhaps even help with some of the above as it's hopefully clear that I've already been thinking about this for a while. I'm not an EE, but I may have some helpful skills. 

Even if you ignore everything I've just typed, I'm likely to buy/build at least a few boards in this space this year, so I really do think you're onto something here!

**Comment by ale1800** [comment]
Hello @robertlipe, thanks for your your great feedback! 

I uploaded the pdf file of the schematic. The module is the ESP32-WROOM-32E, that should still be in production. I know it's quite old, but it's still the only ESP32 to support Wifi and both Classic Bluetooth and BLE and it provides fully compatibility with the most important open source firmware like ESPHome and WLED. On the other hand the advantage of removing all the serial parts is relevant, as the fastest processor that maybe could help for some effects or something similar. Honestly I don't know if it will be a commercial product or not, at the moment is a personal project. in that case I will seriously consider the switch (maybe the s3 mini?) 

In the same case i will try to provide more power at the output, and the power injection is a thing I should keep in mind. I can see that a lot of people use really long strips, so pushing the PD to 24V would be really useful.

I think that the external DC is a good catch, just as a "classic" alternative to the USB-C. Maybe I could also add another terminal for a second independent strip led? 

Thanks very much for your advices!

**Comment by ale1800** [comment]
Sorry, when you say "If you build some", do you mean the 44 pin breakout board or my board with the S3?

Regarding the input, a DC5521 would be absolutely useful, but I think that if someone need a board with that input, should go with the Quinled boards. They are made for that. I think mine would be more expensive and "without reviews" compared to the others.

I checked the WCH board and are quite interesting! My only concern is about if these IC would be reliable as the STUSB4500?

I really appreciate your time to provide valuable suggestions!

**Comment by ale1800** [comment]
I wasn't aware those board were from WCH. Good to know! Based on your experience, is the esp32 s3 native usb reliable? Because, like for the S2, I found a lot of people complaining about it. Last year I tried two ESP32 S2 mini dev board with the USB-C and I've never been able to program them. I also read that all the esp-web-tool do not work very well with the native usb. I always chose the WROOM-32E because of this and software compaitiblity in general

**Comment by ale1800** [comment]
So it seems that the native USB needs a bit more attention compared to the "external" one. I will think about that and give it a try. Thanks for your really detailed explanation! I can confirm that the S3 module's price is the same as Wroom-32E + cp2102n + transistors. Swapping them seems worthy saving a lot of space.

**Comment by ale1800** [comment]
Hi @robert! Can I ask you the reason why with 24V I would not need the power injection? I always have 5V at the input of the strip

**Comment by ale1800** [comment]
Oh ok, Now I got it. Yes I could some jumper to select the output voltage from the buck converter. It's just 2 or 3 more resistors. Does KnightDriver have some mqtt support to use with Home Assistant or other platforms?

**Comment by ale1800** [comment]
Ok, thanks. Good to know👍

**Comment by ale1800** [comment]
Hi @robertlipe! Where can I PM you? Could you give me your email address?

Thanks!
